const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationSpeed,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Exps.rgb,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.DragnDrop.Cnds.IsEnabled,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.log10,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Text.Cnds.IsVisible
	];
};
self.C3_JsPropNameTable = [
	{arkaplan: 0},
	{fullScreenBtn: 0},
	{shareBtn: 0},
	{audioBtn: 0},
	{refreshBtn: 0},
	{phTable: 0},
	{phGosterge: 0},
	{DragDrop: 0},
	{altTup: 0},
	{masaön: 0},
	{masaarka: 0},
	{sehba: 0},
	{altBeher: 0},
	{waterAmount: 0},
	{materialAmount: 0},
	{ustBeher: 0},
	{kücükmusluk: 0},
	{büyükmusluk: 0},
	{tutacak: 0},
	{posX: 0},
	{posY: 0},
	{horizontalPosX: 0},
	{horizontalPosY: 0},
	{dragX: 0},
	{dragY: 0},
	{Tween: 0},
	{ustTup: 0},
	{active: 0},
	{bosaltMusluk: 0},
	{endX: 0},
	{endY: 0},
	{isPlaced: 0},
	{phMetre: 0},
	{doldurMusluk: 0},
	{Sprite: 0},
	{sliderEmpty: 0},
	{sliderFill: 0},
	{minY: 0},
	{maxY: 0},
	{sliderBtn: 0},
	{materialBtnBar: 0},
	{amountCount: 0},
	{color: 0},
	{phValue: 0},
	{materialID: 0},
	{materialBtn: 0},
	{Touch: 0},
	{materialAmountBtn: 0},
	{materialAmountText: 0},
	{sliderText: 0},
	{dolanSu: 0},
	{beherSivi: 0},
	{bosalanSivi: 0},
	{tupSivi: 0},
	{Browser: 0},
	{phText: 0},
	{Audio: 0},
	{outlineObjects: 0},
	{tintButtons: 0},
	{isGameStart: 0},
	{isTutorialComplete: 0},
	{isSelectMaterial: 0},
	{isPhMetreShow: 0},
	{isDoldurMuslukShow: 0},
	{isGostergeShow: 0},
	{isBosaltMuslukShow: 0},
	{beherAnimationSpeed: 0},
	{activeMaterialAmount: 0},
	{activeMaterialColor: 0},
	{activePhValue: 0},
	{activeMaterialID: 0},
	{initialPhValue: 0},
	{soundControl: 0},
	{selectCount: 0},
	{objectUID: 0}
];

self.InstanceType = {
	arkaplan: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	phTable: class extends self.ISpriteInstance {},
	phGosterge: class extends self.ISpriteInstance {},
	altTup: class extends self.ISpriteInstance {},
	masaön: class extends self.ISpriteInstance {},
	masaarka: class extends self.ISpriteInstance {},
	sehba: class extends self.ISpriteInstance {},
	altBeher: class extends self.ISpriteInstance {},
	ustBeher: class extends self.ISpriteInstance {},
	kücükmusluk: class extends self.ISpriteInstance {},
	büyükmusluk: class extends self.ISpriteInstance {},
	tutacak: class extends self.ISpriteInstance {},
	ustTup: class extends self.ISpriteInstance {},
	bosaltMusluk: class extends self.ISpriteInstance {},
	phMetre: class extends self.ISpriteInstance {},
	doldurMusluk: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	sliderEmpty: class extends self.ISpriteInstance {},
	sliderFill: class extends self.ISpriteInstance {},
	sliderBtn: class extends self.ISpriteInstance {},
	materialBtnBar: class extends self.ISpriteInstance {},
	materialBtn: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	materialAmountBtn: class extends self.ISpriteInstance {},
	materialAmountText: class extends self.ITextInstance {},
	sliderText: class extends self.ITextInstance {},
	dolanSu: class extends self.ISpriteInstance {},
	beherSivi: class extends self.ISpriteInstance {},
	bosalanSivi: class extends self.ISpriteInstance {},
	tupSivi: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	phText: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	outlineObjects: class extends self.ISpriteInstance {},
	tintButtons: class extends self.ISpriteInstance {}
}